#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""
Copyright (c) 2013, Sarah Addams All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

Redistributions of source code must retain the above copyright notice, this list
of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright notice, this 
list of conditions and the following disclaimer in the documentation and/or 
other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES 
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The views and conclusions contained in the software and documentation are those 
of the authors and should not be interpreted as representing official policies, 
either expressed or implied, of the FreeBSD Project.
"""

from AvastConfig import engineConfig
from PyQt4 import QtCore, QtGui
import AvastEngine
import AvastUI
import sys
import os

try:
	_encoding = QtGui.QApplication.UnicodeUTF8
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig)

class subAvastDialog(QtGui.QDialog, AvastUI.Ui_AvastDialog):
	def actionTidyExit(self, e):
		# sys.exit(self.m_app.exec_())
		sys.exit(0)
		
	def actionStop(self, e):
		self.pushButtonStartPause.setText(_translate("AvastDialog", "Start", None))		
		self.buttonToggle=False
		
	def actionToggleStartPause(self, e):
		if (self.buttonToggle):
			self.pushButtonStartPause.setText(_translate("AvastDialog", "Start", None))		
			self.buttonToggle=False
		else:
			self.pushButtonStartPause.setText(_translate("AvastDialog", "Pause", None))		
			self.buttonToggle=True
			
	def __init__(self, app):
		self.buttonToggle = False
		self.m_Engine = AvastEngine.AvastEngine()
		
		self.m_app = app
		QtGui.QDialog.__init__(self)
		# Set up the user interface from Designer.
		self.setupUi(self)
		# Connect up the buttons.
		self.pushButtonExit.clicked.connect(self.actionTidyExit)
		self.pushButtonStartPause.clicked.connect(self.actionToggleStartPause)
		self.pushButtonStop.clicked.connect(self.actionStop)
		
if __name__ == "__main__":
	
	app = QtGui.QApplication(sys.argv)
	cfg = engineConfig()	
	if (not cfg.valid()):
		print("Configuration is invalid... o woe...")
		sys.exit(1)
		
	print(cfg.currentProfile())
	print(cfg.getProfileCount())
	print(cfg.getProfileList())
	
	dlg = subAvastDialog(app)
	dlg.show()
	
	sys.exit(0)
	#sys.exit(app.exec_())

